sudo: false

language: python

python: 3.6.6

install:
    - pip install github-backup

script:
    - github-backup.py Richienb --token "29ecaa74d72facf2b16ed722b13332fe570cced0" --repositories --name-regex ^((?!backups).)*$
    - find repositories -type d -execdir tar -zcvf {}.tar.gz {} && rmdir -rf {} \;

    - github-backup.py Richienb --token "29ecaa74d72facf2b16ed722b13332fe570cced0" --gists
    - find gists -type d -execdir tar -zcvf {}.tar.gz {} && rmdir -rf {} \;

after_script:
    - ./commitpush.sh

notifications:
    email: false
