sudo: false

language: python

python: 3.6.6

install:
    - pip install github-backup
    
script:
    - github-backup Richienb --output-directory $TRAVIS_BUILD_DIR/repositories --repositories
    - find repositories -type d -execdir tar -zcvf {}.tar.gz {} && rmdir -rf {} \;

    - github-backup Richienb --output-directory $TRAVIS_BUILD_DIR/gists --gists
    - find gists -type d -execdir tar -zcvf {}.tar.gz {} && rmdir -rf {} \;
    
after_script:
    - ./commitpush.sh
    
notifications:
    email: false
